### ISSUE TITLE
Not able to install Bee

### ISSUE THREAD

**Issue by mrstormlars** [tanglebay/swarm#406]
I am able to install Hornet without issues, but get an error when installing Bee:
![image](https://user-images.githubusercontent.com/21202092/139484664-ac48ed67-5376-49b1-9b3f-77c276e17e98.png)
![image](https://user-images.githubusercontent.com/21202092/139484589-a8076d4e-8771-4322-b4cd-36a2a4346729.png)

I installed Swarm on a Contabo VPS (4 cores, 8 GB RAM, 50GB NVMe SSD),  with Ubuntu 20.04 64bit. I followed this guide when installing the vps and swarm: https://iota-industrie-4-0.blogspot.com/2021/10/tutorial-zur-installation-einer-iota.html )

**Comment by no8ody** [comment]
Hello, the problem was already known and fixed yesterday at 11 pm. There was an error in the API, which led to the fact that the versions could not be queried correctly.

If you still have the error, please create a new issue again.

**Comment by mrstormlars** [comment]
Thanks - it worked now!
