### ISSUE TITLE
 bug in the latest 1.0.3.7 release of SWARM

### ISSUE THREAD

**Issue by richirich32** [tanglebay/swarm#458]
Hello, i guess there is a little bug in the latest 1.0.3.7 release of SWARM. While deploying the proxy a error accurs for the new named "Swarm Dashboard"
![Unbenannt](https://user-images.githubusercontent.com/93480738/145002445-d938b718-75bc-437d-9776-98088cc22162.png)

**Comment by no8ody** [comment]
Bug is fixed with version 1.0.4
