### ISSUE TITLE
Problems with participation events 

### ISSUE THREAD

**Issue by tristanc39** [tanglebay/swarm#493]
I have problems with the participation plugin, it is activated and with the events added, but when I connect with firefly to my node I can't do the pre stake.

They say that you have to add in the publicRoutes

"/api/plugins/participation/events*",
"/api/plugins/participation/outputs*", 
 "/api/plugins/participation/addresses*"

but if i modify this in the config,json, when i start the node it deletes this configuration.

Do you have any solution for this?

**Comment by no8ody** [comment]
If you have problems with your node and the staking in Firelfy, then set the API routes again in the Hornet configuration.

If it works after that, please close the issue.

**Comment by tristanc39** [comment]
Yes , I added this inside swarm in horrnet.cfg and now it works.

hornetApiPublicRoutes="/health,/mqtt,/api/v1/info,/api/v1/tips,/api/v1/messages*,/api/v1/transactions*,/api/v1/milestones*,/api/v1/outputs*,/api/v1/addresses*,/api/v1/treasury,/api/v1/receipts*,/api/plugins/participation/events*,/api/plugins/participation/outputs*,api/plugins/participation/addresses*"

**Comment by no8ody** [comment]
Yes, but next time just do it over the SWARM menu and it should be much easier.
