### ISSUE TITLE
Staking is not been recognized by firefly

### ISSUE THREAD

**Issue by dlt-green** [tanglebay/swarm#504]
in the first step staking is not been recognized by firefly, the events were set by the hornet dashboard.

solution: i must go in swarm config / API / API Routes / select all -> restart hornet
               i must go in swarm config / API / API Routes / deselect all -> restart hornet

after that it works, maybe the last three api routes are not set properly

**Comment by no8ody** [comment]
The issue was already fixed but existing installations just need to go the routes and press okay so the missing routes will be deployed.
