### ISSUE TITLE
Bee can't parse swarm defined peer address

### ISSUE THREAD

**Issue by coderph0x** [tanglebay/swarm#552]
When defining bee peers in the config, bee crashes with "thread 'main' panicked at 'faulty network configuration: ParsingFailed(_insert multiaddr here_)', /root/bee/bee-node/src/config.rs:233:22".

**Comment by no8ody** [comment]
Then you probably entered something wrong, which leads to the error.

**Comment by coderph0x** [comment]
What could be entered wrong here? It asks for IP address, port and alias, the rest is done automatically.

**Comment by no8ody** [comment]
I have tested domain and IP and everything works fine.
Could you please go to the advanced configuration and check the Chrysalis-Mainnet.json config? Please copy the part "network.peering" (change the ip/dns entries).

**Comment by coderph0x** [comment]
Will check tomorrow since I'm not at the pc anymore. Since address and port should be quite self-explanatory, what did you enter in the alias field?
From what I see in the other multiaddr definitions this should be the key hash, shouldn't it? Why is this field named alias? I entered an arbitrary name here.

**Comment by coderph0x** [comment]
Don't know what went wrong the first times I tried. Now everything is working and the alias is an alias.
Sorry for any inconveniences.
