### ISSUE TITLE
Disk space summary of all nodes

### ISSUE THREAD

**Issue by creps** [tanglebay/swarm#587]
It would be a good improvement, to be able to have inside the SWARM menu for example, a section in which the size that occupy in disk each one of the nodes could be seen, a section where it would be the summary in which all the nodes the space that occupy are seen.

At the moment, if we go to the info of each node we can see the size that occupy in disk each one of the nodes separately, but the idea would be to have a section in which all of them would be seen and in a summarized way.

This improvement occurs to me, because more and more databases are growing and it is good to be able to have a global vision of which is the node that is growing more and to be able to make its management easier.

**Comment by no8ody** [comment]
Will be added with #589
