### ISSUE TITLE
Installer on Pi 'Do you want to install SWAM now' can not get passed this question, entered a 'y' -> SWARM installation canceled

### ISSUE THREAD

**Issue by JvdH-NL** [tanglebay/swarm#856]
Repro: removed current installation on PI (PI is up to date). Had some difficulties with running Hornet 2.0, wanted to do a full reinstall.  Remote session to PI (PuTTY). Typing y, Y, ... can't seem to get passed this 'Do you want to install SWAM now?' question.

Used:
sudo ${SHELL:-sh} -c "$(curl -Ls https://cdn.tanglebay.com/swarm/installer/installer.sh)"

Output:
 _______      _  _  _      _______       ______      _______
 |______      |  |  |      |_____|      |_____/      |  |  |
 ______|      |__|__|      |     |      |    \_      |  |  |

=============================================================

Do you want to install SWARM now?(y/N) y

-> SWARM installation canceled.

**Comment by no8ody** [comment]
Hello, which operating system do you use on your raspberry? Should work on Ubuntu 22.04 which is also the recommended OS for SWARM.

**Comment by JvdH-NL** [comment]
Ubuntu 22.10

**Comment by JvdH-NL** [comment]
Made small script, derived from installer file, regex seems to be correct, but eval -> not a 'y'. Very strange:

read -p "Do you want to ${swarmReinstall}install SWARM now?(y/N) " keyboardInput </dev/tty
echo "keyboardInput: $keyboardInput"
keyboardInput=$(echo $keyboardInput | tr '[:upper:]' '[:lower:]')
echo "keyboardInput: $keyboardInput"
if [[ $keyboardInput = ^y* ]]; then
        echo "Yes"
else
        echo "No"
fi

Output:
Do you want to install SWARM now?(y/N) y
keyboardInput: y
keyboardInput: y
No

**Comment by no8ody** [comment]
I have changed the installer a bit, although I think that the changes will unfortunately have no effect but please just give it a try.

**Comment by JvdH-NL** [comment]
Tried new installer: indeed no luck.
Isolated some code + results below:
read -p "Do you want to ${swarmReinstall}install SWARM now?(y/N): " keyboardInput
keyboardInput=$(echo ${keyboardInput,,})
echo "keyboardInput: $keyboardInput"
if [[ $keyboardInput = ^y* ]]; then
        echo "Yes"
else
        echo "No"
fi
Do you want to install SWARM now?(y/N): y
keyboardInput: y
No

**Comment by no8ody** [comment]
I found the issue, please give it another try.

**Comment by JvdH-NL** [comment]
Thanks! It is working!
